// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: HOUZZkitF1_Tester_GUI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x2D6298), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_version = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_version, 0);
    lv_obj_set_y(ui_lb_version, 129);
    lv_obj_set_align(ui_lb_version, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_version, "Checker Ver. 1.0.0");
    lv_obj_set_style_text_color(ui_lb_version, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_version, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_sn_code = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_sn_code, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_sn_code, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_sn_code, 37);
    lv_obj_set_y(ui_lb_sn_code, -5);
    lv_obj_set_align(ui_lb_sn_code, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lb_sn_code, "SN: 1234567890ABC");
    lv_obj_set_style_text_color(ui_lb_sn_code, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_sn_code, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_sn_code, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_title = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_title, lv_pct(75));
    lv_obj_set_height(ui_lb_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_title, 10);
    lv_obj_set_y(ui_lb_title, 80);
    lv_obj_set_align(ui_lb_title, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_lb_title, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_lb_title, "检测通过");
    lv_obj_set_style_text_color(ui_lb_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_title, &ui_font_SYHeiH44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_arrow = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_img_arrow, &ui_img_arrow_png);
    lv_obj_set_width(ui_img_arrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_arrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_img_arrow, 89);
    lv_obj_set_y(ui_img_arrow, 80);
    lv_obj_set_align(ui_img_arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_device_info = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_device_info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_device_info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_device_info, 0);
    lv_obj_set_y(ui_lb_device_info, -110);
    lv_obj_set_align(ui_lb_device_info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_device_info, "设备信息");
    lv_obj_set_style_text_color(ui_lb_device_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_device_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_device_info, &ui_font_SYHeiH18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_firmware = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_firmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_firmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_firmware, 32);
    lv_obj_set_y(ui_lb_firmware, -80);
    lv_obj_set_align(ui_lb_firmware, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lb_firmware, "FW: 2023.1.0");
    lv_obj_set_style_text_color(ui_lb_firmware, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_firmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_firmware, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_error_code = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_error_code, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_error_code, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_error_code, 19);
    lv_obj_set_y(ui_lb_error_code, 20);
    lv_obj_set_align(ui_lb_error_code, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lb_error_code, "Error: 0");
    lv_obj_set_style_text_color(ui_lb_error_code, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_error_code, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_error_code, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_wan_mac = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_wan_mac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_wan_mac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_wan_mac, 5);
    lv_obj_set_y(ui_lb_wan_mac, -55);
    lv_obj_set_align(ui_lb_wan_mac, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lb_wan_mac, "WMac: 00:00:00:00:00:00");
    lv_obj_set_style_text_color(ui_lb_wan_mac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_wan_mac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_wan_mac, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_lan_mac = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lb_lan_mac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_lan_mac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_lan_mac, 14);
    lv_obj_set_y(ui_lb_lan_mac, -30);
    lv_obj_set_align(ui_lb_lan_mac, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lb_lan_mac, "LMac: 00:11:22:33:44:56");
    lv_obj_set_style_text_color(ui_lb_lan_mac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_lan_mac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_lan_mac, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pb_progress = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_pb_progress, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_pb_progress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_pb_progress, 220);
    lv_obj_set_height(ui_pb_progress, 10);
    lv_obj_set_x(ui_pb_progress, 0);
    lv_obj_set_y(ui_pb_progress, 43);
    lv_obj_set_align(ui_pb_progress, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_pb_progress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pb_progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pb_progress, lv_color_hex(0x9FFAC4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pb_progress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pb_progress, lv_color_hex(0x03DA09), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pb_progress, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
