// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: HOUZZkitF1_Tester_GUI

#ifndef _HOUZZKITF1_TESTER_GUI_UI_H
#define _HOUZZKITF1_TESTER_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void tf_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_lb_version;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_SYHeiH);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
